import Link from "next/link";
import { Button } from "@/components/ui/button";
import { auth } from "@/auth";

export default async function Home() {
  const session = await auth();
  return (
    <main className="mx-auto flex min-h-screen max-w-5xl flex-col items-center justify-center px-6 text-center">
      <span className="glass mb-6 rounded-full px-4 py-1.5 text-sm text-white/70">
        ✨ AI-crafted courses from real YouTube tutorials
      </span>
      <h1 className="bg-gradient-to-r from-white to-white/50 bg-clip-text text-5xl font-bold leading-tight text-transparent sm:text-7xl">
        Learn anything.
        <br />
        Your way.
      </h1>
      <p className="mt-6 max-w-xl text-lg text-white/60">
        Tubinator turns any topic into a personalized, structured learning
        journey, generated by AI and matched with the best videos on YouTube.
      </p>
      <div className="mt-10 flex flex-wrap justify-center gap-4">
        {session ? (
          <Link href="/dashboard">
            <Button size="lg">Go to dashboard</Button>
          </Link>
        ) : (
          <>
            <Link href="/register">
              <Button size="lg">Get started free</Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline">
                Sign in
              </Button>
            </Link>
          </>
        )}
      </div>
    </main>
  );
}
