"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";

const TOPICS = [
  "PostgreSQL indexing",
  "React Server Components",
  "Music theory",
  "Options trading",
  "Rust ownership",
  "Watercolor painting",
  "Kubernetes",
  "Spanish grammar",
  "Machine learning",
  "Chess openings",
];

const STEPS = [
  {
    n: "01",
    title: "Tell us a topic",
    body: "Anything from quantum physics to sourdough. Pick your level and your goal.",
  },
  {
    n: "02",
    title: "AI builds the path",
    body: "A structured course of modules and lessons, sequenced from fundamentals to mastery.",
  },
  {
    n: "03",
    title: "Learn from the best",
    body: "Each lesson is matched with the single best YouTube video. Track progress, take notes.",
  },
];

const FEATURES = [
  { t: "Personalized", d: "Courses adapt to your level and goal — no generic playlists." },
  { t: "Curated video", d: "We rank and pick the clearest tutorial for every lesson." },
  { t: "Notes built-in", d: "Capture takeaways on any lesson and revisit them anytime." },
  { t: "Web + Telegram", d: "Learn on the site or right inside our Telegram bot." },
  { t: "Bring your own keys", d: "Plug in your Groq & YouTube keys for unlimited generation." },
  { t: "Progress tracking", d: "Tick off lessons and watch your completion climb." },
];

const fadeUp = {
  hidden: { opacity: 0, y: 28 },
  show: (i = 0) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, delay: i * 0.08, ease: [0.16, 1, 0.3, 1] },
  }),
};

const VP1 = { once: true, margin: "-80px" };
const VP2 = { once: true, margin: "-60px" };
const VP3 = { once: true, margin: "-40px" };
const VP4 = { once: true };
const HOVER = { y: -4 };

export function Landing({ authed }: { authed: boolean }) {
  return (
    <main className="relative">
      {/* HERO */}
      <section className="mx-auto flex min-h-[92vh] max-w-6xl flex-col justify-center px-6 py-24">
        <motion.span
          initial="hidden"
          animate="show"
          variants={fadeUp}
          className="glass mb-8 w-fit rounded-full px-4 py-1.5 text-sm text-white/70"
        >
          ✨ AI-crafted courses from real YouTube tutorials
        </motion.span>

        <motion.h1
          initial="hidden"
          animate="show"
          variants={fadeUp}
          custom={1}
          className="font-display text-6xl font-bold leading-[0.92] tracking-tight sm:text-8xl lg:text-9xl"
        >
          <span className="text-gradient">LEARN</span>
          <br />
          <span className="text-accent-gradient">ANYTHING.</span>
          <br />
          <span className="text-gradient">YOUR WAY.</span>
        </motion.h1>

        <motion.p
          initial="hidden"
          animate="show"
          variants={fadeUp}
          custom={3}
          className="mt-8 max-w-xl text-lg text-white/60"
        >
          Tubinator turns any topic into a personalized, structured learning
          journey — generated by AI and matched with the best videos on YouTube.
        </motion.p>

        <motion.div
          initial="hidden"
          animate="show"
          variants={fadeUp}
          custom={4}
          className="mt-10 flex flex-wrap gap-4"
        >
          {authed ? (
            <Link href="/dashboard">
              <Button size="lg" className="glow">
                Go to dashboard
              </Button>
            </Link>
          ) : (
            <>
              <Link href="/register">
                <Button size="lg" className="glow">
                  Get started free
                </Button>
              </Link>
              <Link href="/login">
                <Button size="lg" variant="outline">
                  Sign in
                </Button>
              </Link>
            </>
          )}
        </motion.div>
      </section>

      {/* MARQUEE */}
      <section className="border-y border-white/10 py-6">
        <div className="marquee">
          {[...TOPICS, ...TOPICS].map((t, i) => (
            <span
              key={i}
              className="font-display text-2xl font-medium text-white/30"
            >
              {t}
              <span className="px-5 text-[hsl(var(--primary))]">◆</span>
            </span>
          ))}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="mx-auto max-w-6xl px-6 py-28">
        <motion.h2
          initial="hidden"
          whileInView="show"
          viewport={VP1}
          variants={fadeUp}
          className="font-display text-4xl font-bold sm:text-5xl"
        >
          From zero to fluent in three steps.
        </motion.h2>
        <div className="mt-14 grid gap-6 md:grid-cols-3">
          {STEPS.map((s, i) => (
            <motion.div
              key={s.n}
              initial="hidden"
              whileInView="show"
              viewport={VP2}
              variants={fadeUp}
              custom={i}
              className="glass rounded-2xl p-7"
            >
              <div className="font-display text-5xl font-bold text-[hsl(var(--primary))]">
                {s.n}
              </div>
              <h3 className="mt-4 text-xl font-semibold">{s.title}</h3>
              <p className="mt-2 text-white/55">{s.body}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* FEATURES */}
      <section className="mx-auto max-w-6xl px-6 pb-28">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f, i) => (
            <motion.div
              key={f.t}
              initial="hidden"
              whileInView="show"
              viewport={VP3}
              variants={fadeUp}
              custom={i}
              whileHover={HOVER}
              className="glass rounded-2xl p-6"
            >
              <h3 className="text-lg font-semibold text-white">{f.t}</h3>
              <p className="mt-1 text-sm text-white/55">{f.d}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-6xl px-6 pb-32">
        <motion.div
          initial="hidden"
          whileInView="show"
          viewport={VP4}
          variants={fadeUp}
          className="glass relative overflow-hidden rounded-3xl px-8 py-20 text-center"
        >
          <div className="pointer-events-none absolute inset-0 -z-10 opacity-40 [background:radial-gradient(60%_60%_at_50%_0%,hsl(var(--primary)/0.5),transparent)]" />
          <h2 className="font-display text-4xl font-bold sm:text-6xl">
            Pick a topic. <span className="text-accent-gradient">Press play.</span>
          </h2>
          <p className="mx-auto mt-4 max-w-md text-white/60">
            Your first course is free. No credit card, just curiosity.
          </p>
          <div className="mt-8 flex justify-center">
            <Link href={authed ? "/dashboard" : "/register"}>
              <Button size="lg" className="glow">
                {authed ? "Go to dashboard" : "Start learning free"}
              </Button>
            </Link>
          </div>
        </motion.div>
        <p className="mt-10 text-center text-sm text-white/30">
          Tubinator · Learn anything, your way.
        </p>
      </section>
    </main>
  );
}
